### ISSUE TITLE
chunkPayloadData/payloadQueue race

### ISSUE THREAD

**Issue by backkem** [pions/sctp#19]
I'm hitting the race below trying to upgrade [backkem/go-libp2p-webrtc-direct](https://github.com/backkem/go-libp2p-webrtc-direct) to the latest pions/webrtc. The problem seems to be that the chunkPayloadData buffers are passed around to multiple goroutines and accessed concurrently. I haven't quite figured it out the details or solution yet thought.

```
==================
WARNING: DATA RACE
Write at 0x00c0005822c0 by goroutine 47:
  encoding/binary.PutUvarint()
      encoding/binary/varint.go:48 +0xb5
  github.com/libp2p/go-mplex.(*Multiplex).sendMsg()
      github.com/libp2p/go-mplex/multiplex.go:155 +0x2bf
  github.com/libp2p/go-mplex.(*Stream).Close()
      github.com/libp2p/go-mplex/stream.go:180 +0x11c
  github.com/libp2p/go-libp2p-transport/test.SubtestPingPong.func1.1()
      github.com/libp2p/go-libp2p-transport/test/transport.go:193 +0x310

Previous read at 0x00c0005822c0 by goroutine 146:
  runtime.slicecopy()
      runtime/slice.go:221 +0x0
  github.com/pions/sctp.(*chunkPayloadData).marshal()
      github.com/pions/sctp/chunk_payload_data.go:134 +0x4dc
  github.com/pions/sctp.(*packet).marshal()
      github.com/pions/sctp/packet.go:129 +0x3f4
  github.com/pions/sctp.(*Association).send()
      github.com/pions/sctp/association.go:930 +0x59
  github.com/pions/sctp.(*Association).handleInbound()
      github.com/pions/sctp/association.go:261 +0x160
  github.com/pions/sctp.(*Association).readLoop()
      github.com/pions/sctp/association.go:226 +0x135

Goroutine 47 (running) created at:
  github.com/libp2p/go-libp2p-transport/test.SubtestPingPong.func1()
      github.com/libp2p/go-libp2p-transport/test/transport.go:168 +0x20f

Goroutine 146 (running) created at:
  github.com/pions/sctp.Client()
      github.com/pions/sctp/association.go:141 +0x86
  github.com/pions/webrtc.(*SCTPTransport).Start()
      github.com/pions/webrtc/sctptransport.go:88 +0x150
  github.com/pions/webrtc.(*PeerConnection).SetRemoteDescription.func2()
      github.com/pions/webrtc/peerconnection.go:843 +0x557
==================
```

**Comment by enobufs** [comment]
```
gitAhub.com/pions/sctp/chunk_payload_data.go:157 +0x4dc
```
With a quick look, this line does not seem to access any resource...  I wonder if you are using the lastest sctp (v1.4.0)...

**Comment by backkem** [comment]
Oh, sorry. I added some debug statements. Will clean and post a new trace.

**Comment by backkem** [comment]
Updated.

**Comment by enobufs** [comment]
It's really hard to tell what is going on just by looking at the warning.

I ran [my code](https://gist.github.com/enobufs/7d8e2996022658b31c04019afac91393) with the latest pions/webrtc but I do not see the race.

If you could tell me how to reproduce the error, I can try it out.

One thing I am suspecting now is, when a payload chunk is passed to reasseblyQueue then becomes "readable" (all fragments are received), reassemblyQueue.read() is called by another goroutine without holding association's lock, which may cause a race... not sure yet.

**Comment by backkem** [comment]
I can currently only reproducy using [backkem/go-libp2p-webrtc-direct](https://github.com/backkem/go-libp2p-webrtc-direct)` which is rather anoying to set up because it also has depencencies that are not up-streamed yet :/

Some things I noticed:
- go-mplex uses a pool of buffers for sending. Meaning, after calling `Stream.WriteSCTP` it will put the buffer in a pool for re-use. If we want to keep this data around for longer, e.g. in the payloadQueue, we need to make a copy.
- This may also have something to do with `Association.getPayloadDataToSend` since the only place where 'Association.send' is called by `Association.handleInbound` with `chunkPayloadData` is as a result of `Association.handleSack`.

I'll try to look into it a bit more.

**Comment by backkem** [comment]
The buffer pool seems to explain the behavior quite well, it seems. If I make a copy of the `chunkPayloadData.userData` in `Association.sendPayloadData` the race is gone. I wonder what the best solution would be. Maybe always make a copy in `Stream.packetize` since we'll have to store the chunks anyway?

**Comment by enobufs** [comment]
Good catch! I think it is natural for the app to reuse the send buffer It is reasonable to make a copy. BSD socket works the same.
